/*
 * QUANTCONNECT.COM - Democratizing Finance, Empowering Individuals.
 * Lean Algorithmic Trading Engine v2.0. Copyright 2014 QuantConnect Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
*/

/*
* QUANTCONNECT.COM - Democratizing Finance, Empowering Individuals.
* Lean Algorithmic Trading Engine v2.2 Copyright 2015 QuantConnect Corporation.
*/

using System.Collections.Generic;
using QuantConnect.Algorithm.Framework.Alphas;

namespace QuantConnect.Packets
{
    /// <summary>
    /// Provides a packet type for transmitting alpha data
    /// </summary>
    public class AlphaResultPacket : Packet
    {
        /// <summary>
        /// The algorithm's unique identifier
        /// </summary>
        public string AlgorithmId { get; set; }

        /// <summary>
        /// The generated alphas
        /// </summary>
        public List<Alpha> Alphas { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="AlphaResultPacket"/> class
        /// </summary>
        public AlphaResultPacket()
            : base(PacketType.AlphaResult)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AlphaResultPacket"/> class
        /// </summary>
        /// <param name="algorithmId">The algorithm's unique identifier</param>
        /// <param name="alphas">Alphas generated by the algorithm</param>
        public AlphaResultPacket(string algorithmId, List<Alpha> alphas)
            : base(PacketType.AlphaResult)
        {
            AlgorithmId = algorithmId;
            Alphas = alphas;
        }
    }
}
