/*
 * QUANTCONNECT.COM - Democratizing Finance, Empowering Individuals.
 * Lean Algorithmic Trading Engine v2.0. Copyright 2014 QuantConnect Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

using QuantConnect.Interfaces;

namespace QuantConnect.Algorithm.CSharp
{
    public class BasicTemplateResearch : IRegressionResearchDefinition
    {
        public string ExpectedOutput => "{\r\n \"cells\": [\r\n  {\r\n   \"cell_type\": \"markdown\",\r\n   \"id\": \"0e6c2e37\",\r\n   \"metadata\": {\r\n    \"papermill\": {\r\n     \"duration\": 0.013112,\r\n     \"end_time\": \"2022-02-25T19:42:14.457240\",\r\n     \"exception\": false,\r\n     \"start_time\": \"2022-02-25T19:42:14.444128\",\r\n" +
            "     \"status\": \"completed\"\r\n    },\r\n    \"tags\": []\r\n   },\r\n   \"source\": [\r\n    \"![QuantConnect Logo](https://cdn.quantconnect.com/web/i/qc_notebook_logo_rev0.png)\\n\",\r\n    \"## Welcome to The QuantConnect Research Page\\n\",\r\n    \"#### Refer to this page for documentation https://www.quantconnect.com/docs/research/overview#\\n\",\r\n" +
            "    \"#### Contribute to this template file https://github.com/QuantConnect/Lean/blob/master/Research/BasicQuantBookTemplate.ipynb\"\r\n   ]\r\n  },\r\n  {\r\n   \"cell_type\": \"markdown\",\r\n   \"id\": \"e8662bdf\",\r\n   \"metadata\": {\r\n    \"papermill\": {\r\n     \"duration\": 0.002996,\r\n     \"end_time\": \"2022-02-25T19:42:14.465410\",\r\n     \"exception\": false,\r\n" +
            "     \"start_time\": \"2022-02-25T19:42:14.462414\",\r\n     \"status\": \"completed\"\r\n    },\r\n    \"tags\": []\r\n   },\r\n   \"source\": [\r\n    \"## QuantBook Basics\\n\",\r\n    \"\\n\",\r\n    \"### Start QuantBook\\n\",\r\n    \"- Add the references and imports\\n\",\r\n    \"- Create a QuantBook instance\"\r\n   ]\r\n  },\r\n  {\r\n" +
            "   \"cell_type\": \"code\",\r\n   \"execution_count\": 1,\r\n   \"id\": \"edc81f42\",\r\n   \"metadata\": {\r\n    \"execution\": {\r\n     \"iopub.execute_input\": \"2022-02-25T19:42:14.480345Z\",\r\n     \"iopub.status.busy\": \"2022-02-25T19:42:14.479345Z\",\r\n     \"iopub.status.idle\": \"2022-02-25T19:42:14.491411Z\",\r\n" +
            "     \"shell.execute_reply\": \"2022-02-25T19:42:14.491411Z\"\r\n    },\r\n    \"papermill\": {\r\n     \"duration\": 0.021989,\r\n     \"end_time\": \"2022-02-25T19:42:14.491411\",\r\n     \"exception\": false,\r\n     \"start_time\": \"2022-02-25T19:42:14.469422\",\r\n     \"status\": \"completed\"\r\n    },\r\n    \"tags\": []\r\n" +
            "   },\r\n   \"outputs\": [],\r\n   \"source\": [\r\n    \"import warnings\\n\",\r\n    \"warnings.filterwarnings(\\\"ignore\\\")\"\r\n   ]\r\n  },\r\n  {\r\n   \"cell_type\": \"code\",\r\n   \"execution_count\": 2,\r\n   \"id\": \"7d215216\",\r\n   \"metadata\": {\r\n    \"execution\": {\r\n     \"iopub.execute_input\": \"2022-02-25T19:42:14.507379Z\",\r\n" +
            "     \"iopub.status.busy\": \"2022-02-25T19:42:14.506350Z\",\r\n     \"iopub.status.idle\": \"2022-02-25T19:42:15.937170Z\",\r\n     \"shell.execute_reply\": \"2022-02-25T19:42:15.936152Z\"\r\n    },\r\n    \"papermill\": {\r\n     \"duration\": 1.438824,\r\n     \"end_time\": \"2022-02-25T19:42:15.937170\",\r\n     \"exception\": false,\r\n" +
            "     \"start_time\": \"2022-02-25T19:42:14.498346\",\r\n     \"status\": \"completed\"\r\n    },\r\n    \"tags\": []\r\n   },\r\n   \"outputs\": [],\r\n   \"source\": [\r\n    \"# Load in our startup script, required to set runtime for PythonNet\\n\",\r\n    \"%run ./start.py\"\r\n   ]\r\n  },\r\n  {\r\n   \"cell_type\": \"code\",\r\n   " +
            "\"execution_count\": 3,\r\n   \"id\": \"30de11e2\",\r\n   \"metadata\": {\r\n    \"execution\": {\r\n     \"iopub.execute_input\": \"2022-02-25T19:42:16.241630Z\",\r\n     \"iopub.status.busy\": \"2022-02-25T19:42:16.240662Z\",\r\n     \"iopub.status.idle\": \"2022-02-25T19:42:16.294630Z\",\r\n     \"shell.execute_reply\": \"2022-02-25T19:42:16.294630Z\"\r\n" +
            "    },\r\n    \"papermill\": {\r\n     \"duration\": 0.35247,\r\n     \"end_time\": \"2022-02-25T19:42:16.294630\",\r\n     \"exception\": false,\r\n     \"start_time\": \"2022-02-25T19:42:15.942160\",\r\n     \"status\": \"completed\"\r\n    },\r\n    \"tags\": []\r\n   },\r\n   \"outputs\": [],\r\n   \"source\": [\r\n    \"# Create an instance\\n\",\r\n" +
            "    \"qb = QuantBook()\\n\",\r\n    \"\\n\",\r\n    \"# Select asset data\\n\",\r\n    \"spy = qb.AddEquity(\\\"SPY\\\")\"\r\n   ]\r\n  },\r\n  {\r\n   \"cell_type\": \"markdown\",\r\n   \"id\": \"fd938eec\",\r\n   \"metadata\": {\r\n    \"papermill\": {\r\n     \"duration\": 0.005002,\r\n     \"end_time\": \"2022-02-25T19:42:16.304630\",\r\n" +
            "     \"exception\": false,\r\n     \"start_time\": \"2022-02-25T19:42:16.299628\",\r\n     \"status\": \"completed\"\r\n    },\r\n    \"tags\": []\r\n   },\r\n   \"source\": [\r\n    \"### Historical Data Requests\\n\",\r\n    \"\\n\",\r\n    \"We can use the QuantConnect API to make Historical Data Requests. The data will be presented as multi-index" +
            " pandas.DataFrame where the first index is the Symbol.\\n\",\r\n    \"\\n\",\r\n    \"For more information, please follow the [link](https://www.quantconnect.com/docs#Historical-Data-Historical-Data-Requests).\"\r\n   ]\r\n  },\r\n  {\r\n   \"cell_type\": \"code\",\r\n   \"execution_count\": 4,\r\n   \"id\": \"13d6aefd\",\r\n   \"metadata\": {\r\n    " +
            "\"execution\": {\r\n     \"iopub.execute_input\": \"2022-02-25T19:42:16.315629Z\",\r\n     \"iopub.status.busy\": \"2022-02-25T19:42:16.314633Z\",\r\n     \"iopub.status.idle\": \"2022-02-25T19:42:16.326629Z\",\r\n     \"shell.execute_reply\": \"2022-02-25T19:42:16.325662Z\"\r\n    },\r\n    \"papermill\": {\r\n     \"duration\": 0.018001,\r\n     " +
            "\"end_time\": \"2022-02-25T19:42:16.326629\",\r\n     \"exception\": false,\r\n     \"start_time\": \"2022-02-25T19:42:16.308628\",\r\n     \"status\": \"completed\"\r\n    },\r\n    \"tags\": []\r\n   },\r\n   \"outputs\": [],\r\n   \"source\": [\r\n    \"startDate = DateTime(2021,1,1)\\n\",\r\n    \"endDate = DateTime(2021,12,31)\"\r\n   ]\r\n  },\r\n" +
            "  {\r\n   \"cell_type\": \"code\",\r\n   \"execution_count\": 5,\r\n   \"id\": \"3223ea4a\",\r\n   \"metadata\": {\r\n    \"execution\": {\r\n     \"iopub.execute_input\": \"2022-02-25T19:42:16.341634Z\",\r\n     \"iopub.status.busy\": \"2022-02-25T19:42:16.340699Z\",\r\n     \"iopub.status.idle\": \"2022-02-25T19:42:16.484609Z\",\r\n     " +
            "\"shell.execute_reply\": \"2022-02-25T19:42:16.483552Z\"\r\n    },\r\n    \"papermill\": {\r\n     \"duration\": 0.153947,\r\n     \"end_time\": \"2022-02-25T19:42:16.484609\",\r\n     \"exception\": false,\r\n     \"start_time\": \"2022-02-25T19:42:16.330662\",\r\n     \"status\": \"completed\"\r\n    },\r\n    \"scrolled\": true,\r\n" +
            "    \"tags\": []\r\n   },\r\n   \"outputs\": [],\r\n   \"source\": [\r\n    \"# Gets historical data from the subscribed assets, the last 360 datapoints with daily resolution\\n\",\r\n    \"h1 = qb.History(qb.Securities.Keys, startDate, endDate, Resolution.Daily)\\n\",\r\n    \"\\n\",\r\n    \"if h1.shape[0] < 1:\\n\",\r\n    \"    raise Exception(\\\"History request resulted in no data\\\")\"\r\n" +
            "   ]\r\n  },\r\n  {\r\n   \"cell_type\": \"markdown\",\r\n   \"id\": \"444b58c7\",\r\n   \"metadata\": {\r\n    \"papermill\": {\r\n     \"duration\": 0.005987,\r\n     \"end_time\": \"2022-02-25T19:42:16.495550\",\r\n     \"exception\": false,\r\n     \"start_time\": \"2022-02-25T19:42:16.489563\",\r\n     \"status\": \"completed\"\r\n    },\r\n    \"tags\": []\r\n   },\r\n" +
            "   \"source\": [\r\n    \"### Indicators\\n\",\r\n    \"\\n\",\r\n    \"We can easily get the indicator of a given symbol with QuantBook. \\n\",\r\n    \"\\n\",\r\n    \"For all indicators, please checkout QuantConnect Indicators [Reference Table](https://www.quantconnect.com/docs#Indicators-Reference-Table)\"\r\n   ]\r\n  },\r\n  {\r\n   \"cell_type\": \"code\",\r\n" +
            "   \"execution_count\": 6,\r\n   \"id\": \"dd79dfe3\",\r\n   \"metadata\": {\r\n    \"execution\": {\r\n     \"iopub.execute_input\": \"2022-02-25T19:42:16.512896Z\",\r\n     \"iopub.status.busy\": \"2022-02-25T19:42:16.512896Z\",\r\n     \"iopub.status.idle\": \"2022-02-25T19:42:16.562892Z\",\r\n     \"shell.execute_reply\": \"2022-02-25T19:42:16.562892Z\"\r\n    },\r\n" +
            "    \"papermill\": {\r\n     \"duration\": 0.063077,\r\n     \"end_time\": \"2022-02-25T19:42:16.562892\",\r\n     \"exception\": false,\r\n     \"start_time\": \"2022-02-25T19:42:16.499815\",\r\n     \"status\": \"completed\"\r\n    },\r\n    \"tags\": []\r\n   },\r\n   \"outputs\": [],\r\n   \"source\": [\r\n    \"# Example with BB, it is a datapoint indicator\\n\",\r\n" +
            "    \"# Define the indicator\\n\",\r\n    \"bb = BollingerBands(30, 2)\\n\",\r\n    \"\\n\",\r\n    \"# Gets historical data of indicator\\n\",\r\n    \"bbdf = qb.Indicator(bb, \\\"SPY\\\", startDate, endDate, Resolution.Daily)\\n\",\r\n    \"\\n\",\r\n    \"# drop undesired fields\\n\",\r\n    \"bbdf = bbdf.drop('standarddeviation', 1)\\n\",\r\n    \"\\n\",\r\n" +
            "    \"if bbdf.shape[0] < 1:\\n\",\r\n    \"    raise Exception(\\\"Bollinger Bands resulted in no data\\\")\"\r\n   ]\r\n  },\r\n  {\r\n   \"cell_type\": \"code\",\r\n   \"execution_count\": null,\r\n   \"id\": \"cb044f0c\",\r\n   \"metadata\": {\r\n    \"papermill\": {\r\n     \"duration\": 0.004737,\r\n     \"end_time\": \"2022-02-25T19:42:16.571976\",\r\n" +
            "     \"exception\": false,\r\n     \"start_time\": \"2022-02-25T19:42:16.567239\",\r\n     \"status\": \"completed\"\r\n    },\r\n    \"tags\": []\r\n   },\r\n   \"outputs\": [],\r\n   \"source\": []\r\n  }\r\n ],\r\n \"metadata\": {\r\n  \"kernelspec\": {\r\n   \"display_name\": \"Python 3 (ipykernel)\",\r\n   \"language\": \"python\",\r\n   \"name\": \"python3\"\r\n" +
            "  },\r\n  \"language_info\": {\r\n   \"codemirror_mode\": {\r\n    \"name\": \"ipython\",\r\n    \"version\": 3\r\n   },\r\n   \"file_extension\": \".py\",\r\n   \"mimetype\": \"text/x-python\",\r\n   \"name\": \"python\",\r\n   \"nbconvert_exporter\": \"python\",\r\n   \"pygments_lexer\": \"ipython3\",\r\n   \"version\": \"3.9.7\"\r\n  },\r\n  \"papermill\": {\r\n" +
            "   \"default_parameters\": {},\r\n   \"duration\": 5.901503,\r\n   \"end_time\": \"2022-02-25T19:42:17.729882\",\r\n   \"environment_variables\": {},\r\n   \"exception\": null,\r\n   \"input_path\": \"D:\\\\quantconnect\\\\Lean\\\\Tests\\\\bin\\\\Debug\\\\BasicTemplateResearch.ipynb\",\r\n   \"output_path\": \"D:\\\\quantconnect\\\\Lean\\\\Tests\\\\bin\\\\Debug\\\\BasicTemplateResearch-output.ipynb\",\r\n" +
            "   \"parameters\": {},\r\n   \"start_time\": \"2022-02-25T19:42:11.828379\",\r\n   \"version\": \"2.3.4\"\r\n  }\r\n },\r\n \"nbformat\": 4,\r\n \"nbformat_minor\": 5\r\n}";
    }
}
