/*
 * QUANTCONNECT.COM - Democratizing Finance, Empowering Individuals.
 * Lean Algorithmic Trading Engine v2.0. Copyright 2014 QuantConnect Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

using System.Collections.Generic;
using System.Linq;
using QuantConnect.Data.Fundamental;
using QuantConnect.Interfaces;
using QuantConnect.Util;

namespace QuantConnect
{
    /// <summary>
    /// Report generated by the <see cref="IDataMonitor"/> class that contains information about missing data
    /// </summary>
    public class DataMonitorReport
    {
        private readonly IReadOnlyCollection<string> _fetchedData;
        private readonly IReadOnlyCollection<string> _missingData;
        
        public int MissingDataCount
        {
            get
            {
                return _missingData.Count;
            }
        }

        public double MissingDataPercentage
        {
            get
            {
                var requestsCount = _fetchedData.Count + _missingData.Count;

                if (requestsCount == 0)
                {
                    return 0;
                }

                return _missingData.Count / (double)requestsCount * 100;
            }
        }

        public DataMonitorReport(HashSet<string> fetchedData, HashSet<string> missingData)
        {
            _fetchedData = fetchedData;
            _missingData = missingData;
        }
    }
}
