/* 
 *  # API versions   We supports several API versions simultaneously:   - Current **stable** API version is 2.0, version 1.0 is deprecated.   - API version 3.0 is **under development** and subject to change. We plan to freeze this API version at the late 2020.  # Limitations   Current API has the following limitations:   - URL should not be longer than 2000 symbols   - Maximal order depth for both archive and active orders is limited   by settings (1000 by default)  # Authentication  Bridge offers two form of authentication:   - HTTP Basic auth   - [JWT token](https://jwt.io) auth, which can be used as both authorization header and query parameter. Only HS256   (HMAC-SHA256) signature algo is supported. `iss` claim is used to pass clientId, `sub` is for application id. For example,   build JWT from following parts:    header:    ```   { \"alg\": \"HS256\", \"typ\": \"JWT\" }   ```    payload:    ```   {     \"sub\": \"77b378e8-3a30-4f85-9017-e839501f7589\",     \"iss\": \"469a8180-51fb-408f-a1f0-c3775eeb6ade\",     \"iat\": 1481850484,     \"aud\": [       \"feed\",       \"symbols\",       \"ohlc\",       \"crossrates\"     ]   }   ```    base64-encoded and concatenated with dot:    ```   eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3N2IzNzhlOC0zYTMwLTRmODUtOTAxNy1lODM5NTAxZjc1ODkiLCJpc3MiOiI0NjlhODE4MC01MWZiLTQwOGYtYTFmMC1jMzc3NWVlYjZhZGUiLCJpYXQiOjE0ODE4NTA0ODQsImF1ZCI6WyJmZWVkIiwic3ltYm9scyIsIm9obGMiLCJjcm9zc3JhdGVzIl19   ```    and finally signed with shared secret:    ```   eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3N2IzNzhlOC0zYTMwLTRmODUtOTAxNy1lODM5NTAxZjc1ODkiLCJpc3MiOiI0NjlhODE4MC01MWZiLTQwOGYtYTFmMC1jMzc3NWVlYjZhZGUiLCJpYXQiOjE0ODE4NTA0ODQsImF1ZCI6WyJmZWVkIiwic3ltYm9scyIsIm9obGMiLCJjcm9zc3JhdGVzIl19.Byn6aPDoMnaQUSGMnnddj2rI-noP9cQwa8JLJswgNGk   ```  <security-definitions />       
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IAccountSummaryAPIApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// get account summary by date
        /// </summary>
        /// <remarks>
        /// Return the summary for the specified account and session date
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">API version</param>
        /// <param name="id">account id to get summary</param>
        /// <param name="date">session date of the account summary</param>
        /// <param name="currency">currency to convert summary</param>
        /// <returns>AccountSummaryResponse</returns>
        AccountSummaryResponse GetAccountSummary (string version, string id, string date, string currency);

        /// <summary>
        /// get account summary by date
        /// </summary>
        /// <remarks>
        /// Return the summary for the specified account and session date
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">API version</param>
        /// <param name="id">account id to get summary</param>
        /// <param name="date">session date of the account summary</param>
        /// <param name="currency">currency to convert summary</param>
        /// <returns>ApiResponse of AccountSummaryResponse</returns>
        ApiResponse<AccountSummaryResponse> GetAccountSummaryWithHttpInfo (string version, string id, string date, string currency);
        /// <summary>
        /// get account summary
        /// </summary>
        /// <remarks>
        /// Return the summary for the specified account
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">API version</param>
        /// <param name="id">account id to get summary</param>
        /// <param name="currency">currency to convert summary</param>
        /// <returns>AccountSummaryResponse</returns>
        AccountSummaryResponse GetAccountSummaryWithoutDate (string version, string id, string currency);

        /// <summary>
        /// get account summary
        /// </summary>
        /// <remarks>
        /// Return the summary for the specified account
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">API version</param>
        /// <param name="id">account id to get summary</param>
        /// <param name="currency">currency to convert summary</param>
        /// <returns>ApiResponse of AccountSummaryResponse</returns>
        ApiResponse<AccountSummaryResponse> GetAccountSummaryWithoutDateWithHttpInfo (string version, string id, string currency);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// get account summary by date
        /// </summary>
        /// <remarks>
        /// Return the summary for the specified account and session date
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">API version</param>
        /// <param name="id">account id to get summary</param>
        /// <param name="date">session date of the account summary</param>
        /// <param name="currency">currency to convert summary</param>
        /// <returns>Task of AccountSummaryResponse</returns>
        System.Threading.Tasks.Task<AccountSummaryResponse> GetAccountSummaryAsync (string version, string id, string date, string currency);

        /// <summary>
        /// get account summary by date
        /// </summary>
        /// <remarks>
        /// Return the summary for the specified account and session date
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">API version</param>
        /// <param name="id">account id to get summary</param>
        /// <param name="date">session date of the account summary</param>
        /// <param name="currency">currency to convert summary</param>
        /// <returns>Task of ApiResponse (AccountSummaryResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<AccountSummaryResponse>> GetAccountSummaryAsyncWithHttpInfo (string version, string id, string date, string currency);
        /// <summary>
        /// get account summary
        /// </summary>
        /// <remarks>
        /// Return the summary for the specified account
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">API version</param>
        /// <param name="id">account id to get summary</param>
        /// <param name="currency">currency to convert summary</param>
        /// <returns>Task of AccountSummaryResponse</returns>
        System.Threading.Tasks.Task<AccountSummaryResponse> GetAccountSummaryWithoutDateAsync (string version, string id, string currency);

        /// <summary>
        /// get account summary
        /// </summary>
        /// <remarks>
        /// Return the summary for the specified account
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">API version</param>
        /// <param name="id">account id to get summary</param>
        /// <param name="currency">currency to convert summary</param>
        /// <returns>Task of ApiResponse (AccountSummaryResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<AccountSummaryResponse>> GetAccountSummaryWithoutDateAsyncWithHttpInfo (string version, string id, string currency);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class AccountSummaryAPIApi : IAccountSummaryAPIApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountSummaryAPIApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AccountSummaryAPIApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountSummaryAPIApi"/> class
        /// </summary>
        /// <returns></returns>
        public AccountSummaryAPIApi()
        {
            this.Configuration = IO.Swagger.Client.Configuration.Default;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountSummaryAPIApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AccountSummaryAPIApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// get account summary by date Return the summary for the specified account and session date
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">API version</param>
        /// <param name="id">account id to get summary</param>
        /// <param name="date">session date of the account summary</param>
        /// <param name="currency">currency to convert summary</param>
        /// <returns>AccountSummaryResponse</returns>
        public AccountSummaryResponse GetAccountSummary (string version, string id, string date, string currency)
        {
             ApiResponse<AccountSummaryResponse> localVarResponse = GetAccountSummaryWithHttpInfo(version, id, date, currency);
             return localVarResponse.Data;
        }

        /// <summary>
        /// get account summary by date Return the summary for the specified account and session date
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">API version</param>
        /// <param name="id">account id to get summary</param>
        /// <param name="date">session date of the account summary</param>
        /// <param name="currency">currency to convert summary</param>
        /// <returns>ApiResponse of AccountSummaryResponse</returns>
        public ApiResponse< AccountSummaryResponse > GetAccountSummaryWithHttpInfo (string version, string id, string date, string currency)
        {
            // verify the required parameter 'version' is set
            if (version == null)
                throw new ApiException(400, "Missing required parameter 'version' when calling AccountSummaryAPIApi->GetAccountSummary");
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling AccountSummaryAPIApi->GetAccountSummary");
            // verify the required parameter 'date' is set
            if (date == null)
                throw new ApiException(400, "Missing required parameter 'date' when calling AccountSummaryAPIApi->GetAccountSummary");
            // verify the required parameter 'currency' is set
            if (currency == null)
                throw new ApiException(400, "Missing required parameter 'currency' when calling AccountSummaryAPIApi->GetAccountSummary");

            var localVarPath = "/md/{version}/summary/{id}/{date}/{currency}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (version != null) localVarPathParams.Add("version", this.Configuration.ApiClient.ParameterToString(version)); // path parameter
            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (date != null) localVarPathParams.Add("date", this.Configuration.ApiClient.ParameterToString(date)); // path parameter
            if (currency != null) localVarPathParams.Add("currency", this.Configuration.ApiClient.ParameterToString(currency)); // path parameter
            // authentication (basic auth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (jwt token header) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }
            // authentication (jwt token query) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("token")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "token", this.Configuration.GetApiKeyWithPrefix("token")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAccountSummary", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AccountSummaryResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (AccountSummaryResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AccountSummaryResponse)));
        }

        /// <summary>
        /// get account summary by date Return the summary for the specified account and session date
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">API version</param>
        /// <param name="id">account id to get summary</param>
        /// <param name="date">session date of the account summary</param>
        /// <param name="currency">currency to convert summary</param>
        /// <returns>Task of AccountSummaryResponse</returns>
        public async System.Threading.Tasks.Task<AccountSummaryResponse> GetAccountSummaryAsync (string version, string id, string date, string currency)
        {
             ApiResponse<AccountSummaryResponse> localVarResponse = await GetAccountSummaryAsyncWithHttpInfo(version, id, date, currency);
             return localVarResponse.Data;

        }

        /// <summary>
        /// get account summary by date Return the summary for the specified account and session date
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">API version</param>
        /// <param name="id">account id to get summary</param>
        /// <param name="date">session date of the account summary</param>
        /// <param name="currency">currency to convert summary</param>
        /// <returns>Task of ApiResponse (AccountSummaryResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<AccountSummaryResponse>> GetAccountSummaryAsyncWithHttpInfo (string version, string id, string date, string currency)
        {
            // verify the required parameter 'version' is set
            if (version == null)
                throw new ApiException(400, "Missing required parameter 'version' when calling AccountSummaryAPIApi->GetAccountSummary");
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling AccountSummaryAPIApi->GetAccountSummary");
            // verify the required parameter 'date' is set
            if (date == null)
                throw new ApiException(400, "Missing required parameter 'date' when calling AccountSummaryAPIApi->GetAccountSummary");
            // verify the required parameter 'currency' is set
            if (currency == null)
                throw new ApiException(400, "Missing required parameter 'currency' when calling AccountSummaryAPIApi->GetAccountSummary");

            var localVarPath = "/md/{version}/summary/{id}/{date}/{currency}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (version != null) localVarPathParams.Add("version", this.Configuration.ApiClient.ParameterToString(version)); // path parameter
            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (date != null) localVarPathParams.Add("date", this.Configuration.ApiClient.ParameterToString(date)); // path parameter
            if (currency != null) localVarPathParams.Add("currency", this.Configuration.ApiClient.ParameterToString(currency)); // path parameter
            // authentication (basic auth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (jwt token header) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }
            // authentication (jwt token query) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("token")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "token", this.Configuration.GetApiKeyWithPrefix("token")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAccountSummary", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AccountSummaryResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (AccountSummaryResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AccountSummaryResponse)));
        }

        /// <summary>
        /// get account summary Return the summary for the specified account
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">API version</param>
        /// <param name="id">account id to get summary</param>
        /// <param name="currency">currency to convert summary</param>
        /// <returns>AccountSummaryResponse</returns>
        public AccountSummaryResponse GetAccountSummaryWithoutDate (string version, string id, string currency)
        {
             ApiResponse<AccountSummaryResponse> localVarResponse = GetAccountSummaryWithoutDateWithHttpInfo(version, id, currency);
             return localVarResponse.Data;
        }

        /// <summary>
        /// get account summary Return the summary for the specified account
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">API version</param>
        /// <param name="id">account id to get summary</param>
        /// <param name="currency">currency to convert summary</param>
        /// <returns>ApiResponse of AccountSummaryResponse</returns>
        public ApiResponse< AccountSummaryResponse > GetAccountSummaryWithoutDateWithHttpInfo (string version, string id, string currency)
        {
            // verify the required parameter 'version' is set
            if (version == null)
                throw new ApiException(400, "Missing required parameter 'version' when calling AccountSummaryAPIApi->GetAccountSummaryWithoutDate");
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling AccountSummaryAPIApi->GetAccountSummaryWithoutDate");
            // verify the required parameter 'currency' is set
            if (currency == null)
                throw new ApiException(400, "Missing required parameter 'currency' when calling AccountSummaryAPIApi->GetAccountSummaryWithoutDate");

            var localVarPath = "/md/{version}/summary/{id}/{currency}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (version != null) localVarPathParams.Add("version", this.Configuration.ApiClient.ParameterToString(version)); // path parameter
            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (currency != null) localVarPathParams.Add("currency", this.Configuration.ApiClient.ParameterToString(currency)); // path parameter
            // authentication (basic auth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (jwt token header) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }
            // authentication (jwt token query) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("token")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "token", this.Configuration.GetApiKeyWithPrefix("token")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAccountSummaryWithoutDate", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AccountSummaryResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (AccountSummaryResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AccountSummaryResponse)));
        }

        /// <summary>
        /// get account summary Return the summary for the specified account
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">API version</param>
        /// <param name="id">account id to get summary</param>
        /// <param name="currency">currency to convert summary</param>
        /// <returns>Task of AccountSummaryResponse</returns>
        public async System.Threading.Tasks.Task<AccountSummaryResponse> GetAccountSummaryWithoutDateAsync (string version, string id, string currency)
        {
             ApiResponse<AccountSummaryResponse> localVarResponse = await GetAccountSummaryWithoutDateAsyncWithHttpInfo(version, id, currency);
             return localVarResponse.Data;

        }

        /// <summary>
        /// get account summary Return the summary for the specified account
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">API version</param>
        /// <param name="id">account id to get summary</param>
        /// <param name="currency">currency to convert summary</param>
        /// <returns>Task of ApiResponse (AccountSummaryResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<AccountSummaryResponse>> GetAccountSummaryWithoutDateAsyncWithHttpInfo (string version, string id, string currency)
        {
            // verify the required parameter 'version' is set
            if (version == null)
                throw new ApiException(400, "Missing required parameter 'version' when calling AccountSummaryAPIApi->GetAccountSummaryWithoutDate");
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling AccountSummaryAPIApi->GetAccountSummaryWithoutDate");
            // verify the required parameter 'currency' is set
            if (currency == null)
                throw new ApiException(400, "Missing required parameter 'currency' when calling AccountSummaryAPIApi->GetAccountSummaryWithoutDate");

            var localVarPath = "/md/{version}/summary/{id}/{currency}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (version != null) localVarPathParams.Add("version", this.Configuration.ApiClient.ParameterToString(version)); // path parameter
            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (currency != null) localVarPathParams.Add("currency", this.Configuration.ApiClient.ParameterToString(currency)); // path parameter
            // authentication (basic auth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (jwt token header) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }
            // authentication (jwt token query) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("token")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "token", this.Configuration.GetApiKeyWithPrefix("token")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAccountSummaryWithoutDate", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AccountSummaryResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (AccountSummaryResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AccountSummaryResponse)));
        }

    }
}
