/* 
 * OANDA v20 REST API
 *
 * The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * OpenAPI spec version: 3.0.15
 * Contact: api@oanda.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Oanda.RestV20.Model
{
    /// <summary>
    /// The reason that an Account is being funded.
    /// </summary>
    /// <value>The reason that an Account is being funded.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum FundingReason
    {
        
        /// <summary>
        /// Enum CLIENTFUNDING for "CLIENT_FUNDING"
        /// </summary>
        [EnumMember(Value = "CLIENT_FUNDING")]
        CLIENTFUNDING,
        
        /// <summary>
        /// Enum ACCOUNTTRANSFER for "ACCOUNT_TRANSFER"
        /// </summary>
        [EnumMember(Value = "ACCOUNT_TRANSFER")]
        ACCOUNTTRANSFER,
        
        /// <summary>
        /// Enum DIVISIONMIGRATION for "DIVISION_MIGRATION"
        /// </summary>
        [EnumMember(Value = "DIVISION_MIGRATION")]
        DIVISIONMIGRATION,
        
        /// <summary>
        /// Enum SITEMIGRATION for "SITE_MIGRATION"
        /// </summary>
        [EnumMember(Value = "SITE_MIGRATION")]
        SITEMIGRATION,
        
        /// <summary>
        /// Enum ADJUSTMENT for "ADJUSTMENT"
        /// </summary>
        [EnumMember(Value = "ADJUSTMENT")]
        ADJUSTMENT
    }

}
