/* 
 * OANDA v20 REST API
 *
 * The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * OpenAPI spec version: 3.0.15
 * Contact: api@oanda.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Oanda.RestV20.Model
{
    /// <summary>
    /// The reason that the Market Order was created to perform a margin closeout
    /// </summary>
    /// <value>The reason that the Market Order was created to perform a margin closeout</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum MarketOrderMarginCloseoutReason
    {
        
        /// <summary>
        /// Enum MARGINCHECKVIOLATION for "MARGIN_CHECK_VIOLATION"
        /// </summary>
        [EnumMember(Value = "MARGIN_CHECK_VIOLATION")]
        MARGINCHECKVIOLATION,
        
        /// <summary>
        /// Enum REGULATORYMARGINCALLVIOLATION for "REGULATORY_MARGIN_CALL_VIOLATION"
        /// </summary>
        [EnumMember(Value = "REGULATORY_MARGIN_CALL_VIOLATION")]
        REGULATORYMARGINCALLVIOLATION
    }

}
