/* 
 * OANDA v20 REST API
 *
 * The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * OpenAPI spec version: 3.0.15
 * Contact: api@oanda.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Oanda.RestV20.Model
{
    /// <summary>
    /// Specification of what component of a price should be used for comparison when determining if the Order should be filled.
    /// </summary>
    /// <value>Specification of what component of a price should be used for comparison when determining if the Order should be filled.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OrderTriggerCondition
    {
        
        /// <summary>
        /// Enum DEFAULT for "DEFAULT"
        /// </summary>
        [EnumMember(Value = "DEFAULT")]
        DEFAULT,
        
        /// <summary>
        /// Enum TRIGGERDEFAULT for "TRIGGER_DEFAULT"
        /// </summary>
        [EnumMember(Value = "TRIGGER_DEFAULT")]
        TRIGGERDEFAULT,
        
        /// <summary>
        /// Enum INVERSE for "INVERSE"
        /// </summary>
        [EnumMember(Value = "INVERSE")]
        INVERSE,
        
        /// <summary>
        /// Enum BID for "BID"
        /// </summary>
        [EnumMember(Value = "BID")]
        BID,
        
        /// <summary>
        /// Enum ASK for "ASK"
        /// </summary>
        [EnumMember(Value = "ASK")]
        ASK,
        
        /// <summary>
        /// Enum MID for "MID"
        /// </summary>
        [EnumMember(Value = "MID")]
        MID
    }

}
